### ISSUE TITLE
Error in HomeBridge

### ISSUE THREAD

**Issue by shagga101** [fanta759/homebridge-jeedom-platform#16]
**Hello Fanta759,

I run homebridge latest verion and I have this error below. Any idea ?

Thanks !

Shagga**

TypeError: Could not deserialize JeedomCmdConfiguration.returnStateValue: expected 'String', got 'Number'.
    at deserializeDirectly (/usr/lib/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:224:15)
    at Deserializer.convertSingleValue (/usr/lib/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:121:20)
    at /usr/lib/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:317:45
    at Map.forEach (<anonymous>)
    at convertAsObject (/usr/lib/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:294:36)
    at Deserializer.convertSingleValue (/usr/lib/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:132:20)
    at /usr/lib/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:317:45
    at Map.forEach (<anonymous>)
    at convertAsObject (/usr/lib/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:294:36)
    at Deserializer.convertSingleValue (/usr/lib/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:132:20)

**Comment by shagga101** [comment]
I changed the Root ID to test. Not the same error anymore. I HAve this now:

[18/05/2022, 21:48:56] [Jeedom] Registering new accessory: Temp - Bureau Rez - rfx : 4d134bc0-7221-42ac-a2df-385dae143139
[18/05/2022, 21:48:56] [Jeedom] Registering new accessory: Volet roulant W - Bureau Fenetre : 80e28a51-cbc2-46fa-8bd3-4938c5e593b3
[Volet roulant W - Bureau Fenetre@@Serial Number] [Serial Number] characteristic must have a length of more than 1 character otherwise         HomeKit will reject this accessory, ignoring new value
[18/05/2022, 21:48:56] [Jeedom] Registering new accessory: Volet roulant W - Bureau porte Fenetre : 8effee40-9c62-45e1-a2d8-f5033631840e
[Volet roulant W - Bureau porte Fenetre@@Serial Number] [Serial Number] characteristic must have a length of more than 1 character otherwise         HomeKit will reject this accessory, ignoring new value

**Comment by fanta759** [comment]
Hi @shagga101, only Lamp are supported from now.
I don't have any other accessories to test their registration in homebridge
