### ISSUE TITLE
Failed to load plugins config schema

### ISSUE THREAD

**Issue by tdufaud** [fanta759/homebridge-jeedom-platform#7]
Hello,
I'm unable to run this plugin.
Error  : "Failed to load plugins config schema" when trying to manage the plugin config and after installation.
-Homebridge version : 1.3.4
-homebridge-config-ui-x version : 4.41.2
-Jeedom v3.3.57 or v4.1.25

Trying to change manually the homebridge config (log file) : 

TypeError: Could not deserialize JeedomCmdConfiguration.minValue: expected 'String', got 'Number'.
    at deserializeDirectly (/homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:223:15)
    at Deserializer.convertSingleValue (/homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:120:20)
    at /homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:307:45
    at Map.forEach (<anonymous>)
    at convertAsObject (/homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:293:36)
    at Deserializer.convertSingleValue (/homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:131:20)
    at /homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:307:45
    at Map.forEach (<anonymous>)
    at convertAsObject (/homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:293:36)
    at Deserializer.convertSingleValue (/homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:131:20)
TypeError: Could not deserialize JeedomCmdConfiguration.returnStateValue: expected 'String', got 'Number'. 

Thks for your help.

**Comment by fanta759** [comment]
There is a new beta version.
Can you try it ? And take me your feedback ?
Thk

**Comment by tdufaud** [comment]
version 1.0.3-0 installed without error. No config schema error and now access to the config page. :)
But when I restart the homebridge server, there is the following error (repeated 16 times) : 


TypeError: Could not deserialize JeedomEqLogic.logicalId: expected 'String', got 'Array'.
    at deserializeDirectly (/homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:223:15)
    at Deserializer.convertSingleValue (/homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:120:20)
    at /homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:307:45
    at Map.forEach (<anonymous>)
    at convertAsObject (/homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:293:36)
    at Deserializer.convertSingleValue (/homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:131:20)
    at /homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:437:33
    at Array.map (<anonymous>)
    at convertAsArray (/homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:432:25)
    at Deserializer.convertSingleValue (/homebridge/node_modules/homebridge-jeedom-platform/node_modules/typedjson/src/deserializer.ts:120:20)

**Comment by fanta759** [comment]
Hi, Can you give me the result in JSON of this url please ?
http://JEEDOMURL/core/api/jeeApi.php?apikey=YOURAPIKEY&type=object
Replace JEEDOMURL with the url of your jeedom and YOURAPIKEY with yours.
Thk

**Comment by fanta759** [comment]
And please give me the full log of Homebridge ?

**Comment by tdufaud** [comment]
[Output_request.txt](https://github.com/fanta759/homebridge-jeedom-platform/files/7250936/Output_request.txt)
[homebridge.log.txt](https://github.com/fanta759/homebridge-jeedom-platform/files/7250937/homebridge.log.txt)

**Comment by tdufaud** [comment]
Here files attached.

**Comment by fanta759** [comment]
Ok thk for these elements.
I try to reproduce by i don't give your error.
What's your node version ?
Can you activate the debug mode of Homebrige and give me the full log again please ?

**Comment by tdufaud** [comment]
Log file attached.
node version : 14.17.1
Homebridge installed on Docker (Synology 720+ / DSM 7)
[homebridge.log (1).txt](https://github.com/fanta759/homebridge-jeedom-platform/files/7276662/homebridge.log.1.txt)
.

**Comment by fanta759** [comment]
Do you installed hombridge with this tuto ?
https://github.com/oznu/homebridge-syno-spk#how-to-install

**Comment by tdufaud** [comment]
no, this one : https://digitalboxweb.wordpress.com/2021/05/20/utiliser-homebridge-sous-nas-synology/

**Comment by moux2003** [comment]
Hello,
J'ai eu le meme soucis avant de me rendre compte que ça venait certainement d'un type non supporté car j'ai des volets, sondes etc dans Jeedom.
Ex de json:
```json
    "id": "39",
    "logicalId": "position_sliderOpen",
    "generic_type": "FLAP_SLIDER",
    "eqType": "klf200",
    "name": "Définir niveau ouverture en ",
    "order": "4",
    "type": "action",
    "subType": "slider",
    "eqLogic_id": "10",
    "isHistorized": "0",
    "unite": "",
    "configuration": {
        "action": "set",
        "minValue": 0,
        "maxValue": 100,
        "type": "open",
        "request": ""
    },
    "template": {
        "dashboard": "core::default",
        "mobile": "core::default"
    },
    "display": {
        "showStatsOnmobile": 0,
        "showStatsOndashboard": 0,
        "icon": ""
    },
    "value": "",
    "isVisible": "1",
    "alert": []
```

**Comment by fanta759** [comment]
En effet, le plugin ne gère que les lumières pour le moment.
Je n'avais pas d'autres accessoires pour tester.

**Comment by fanta759** [comment]
@tdufaud Do you still have the error with the plugin ?
